--- #YAML:1.0
name:               Dpchrist-File-Find-Duplicates
version:            1.018
abstract:           find duplicate files
author:
    - David Paul Christensen <dpchrist@holgerdanske.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 1.08
    Digest::MD5:          2.3601
    Dpchrist::Debug:      1.049
    Exporter:             5.62
    ExtUtils::MakeMaker:  6.54
    File::Compare:        1.1005
    File::Find:           1.12
    Getopt::Long:         2.37
    Pod::Usage:           1.35
    Test::Compile:        0.1
    Test::Manifest:       1.22
    Test::More:           0.72
    Test::Pod:            1.4
    Test::Prereq:         1.037
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
